### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by codingwatching** [cohaereo/minecrab#1]
Hi @cohaereo 
Can you support building minecrab for android devices?
Thank you so much!

**Comment by cohaereo** [comment]
Definitely an interesting point, I might look into it soon, thanks to wgpu and Rust this shouldn't be that difficult.

One problem right now is the lack of a user interface, though that might not be such a big problem during development.

**Comment by codingwatching** [comment]
@cohaereo Thank you so much! I can install and test it for you!

**Comment by cohaereo** [comment]
Might also be interesting to try and add WebAssembly support. 
One big problem with that is that is that browsers do not support TCP sockets. One could consider creating a TCP-over-WebSocket proxy server, but that seems like a big pain point that cant be solved without a dedicated host.

Of course one could also use a WASM version to create a "universal" port of sorts, but i feel like that would bring too much overhead for it to be viable vs. a native build.

**Comment by cohaereo** [comment]
I've also created an issue tracker for Android support #2
